### PR TITLE
Get the source_dlopen test working

### PR DESCRIPTION
**Pull request by paulromano**
Hi @makeclean. This should hopefully get the regression test working. I've replaced your shell script with standard Python function calls along with use of `subprocess`.

### CODE REVIEW

**Comment by shimwell** [comment]
The only failure is coming from the DAGMC build, in which case libopenmc also depends upon the DAGMC libraries, so we need to find some way of passing through the DAGMC libraries
```
/usr/bin/ld: cannot find -lMOAB
/usr/bin/ld: cannot find -ldagmc
/usr/bin/ld: cannot find -lpyne_dagmc
/usr/bin/ld: cannot find -luwuw
/usr/bin/ld: cannot find -ldagtally
/usr/bin/ld: cannot find -lmakeWatertight
```

**Comment by paulromano** [comment]
Yeah, I noticed that too. The real problem is that DAGMC and MOAB don't export targets properly from their CMake files (@pshriwise maybe you can ping the right people about getting that fixed). I'm working on a temporary fix in OpenMC now though.

**Comment by pshriwise** [comment]
I was just looking at exporting targets from DAGMC this week and have a branch ready to go for exporting targets from DAGMC (going to PR today). MOAB does in fact export their targets... as long as MOAB is built with CMake, which is not currently required by DAGMC. There has been some discussion of [ditching support for MOAB builds with autotools](https://github.com/svalinn/DAGMC/pull/634#issuecomment-531805264), but I don't see that happening anytime soon necessarily.

**Comment by pshriwise** [comment]
PR opened: https://github.com/svalinn/DAGMC/pull/662

**Comment by paulromano** [comment]
I submitted a fix for the DAGMC issue as a separate PR (openmc-dev/openmc#1490). Once that gets merged, triggering a rebuild of this branch should pass all tests.

**Comment by paulromano** [comment]
openmc-dev/openmc#1490 was merged, so if you merge this branch into yours, we should get tests passing now (note that when Travis runs tests for a pull request, it will actually do it for a merge commit with `develop`, not the branch itself).

**Comment by makeclean** [comment]
Lets go!

**Pull request merged**
